site_name: Justin Hsiung's Space
theme:
  name: material
  custom_dir: overrides
  palette: 
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  logo: assets/bear-head-svgrepo-com.svg
  favicon: assets/bear-head-svgrepo-com.svg
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.footer
    - navigation.top
plugins:
  - tags:
      tags_file: tags.md
  - search:
      lang: en
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/JustinBear99
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/hsien-feng-hsiung/
nav:
  - Home: index.md
  - Career:
    - career/index.md
    - Leet Code:
      - career/leetcode/index.md
      - Daily:
        - Oct 2023:
          - career/leetcode/daily/oct2023/823-binary-trees-with-factors.md
          - career/leetcode/daily/oct2023/5-longest-palindromic-substring.md
          - career/leetcode/daily/oct2023/1220-count-vowels-permutation.md
          - career/leetcode/daily/oct2023/458-poor-pigs.md
          - career/leetcode/daily/oct2023/1356-sort-integers-by-the-number-of-1-bits.md
          - career/leetcode/daily/oct2023/2433-find-the-original-array-of-prefix-xor.md
        - Nov 2023:
          - career/leetcode/daily/nov2023/501-find-mode-in-binary-search-tree.md
          - career/leetcode/daily/nov2023/2265-count-nodes-equal-to-average-of-subtree.md
          - career/leetcode/daily/nov2023/1441-build-an-array-with-stack-operations.md
          - career/leetcode/daily/nov2023/1503-last-moment-before-all-ants-fall-out-of-a-plank.md
          - career/leetcode/daily/nov2023/1535-find-the-winner-of-an-array-game.md
          - career/leetcode/daily/nov2023/1845-seat-reservation-manager.md
          - career/leetcode/daily/nov2023/1921-eliminate-maximum-number-of-monsters.md
          - career/leetcode/daily/nov2023/1759-count-number-of-homogenous-substrings.md
          - career/leetcode/daily/nov2023/1743-restore-the-array-from-adjacent-pairs.md
          - career/leetcode/daily/nov2023/2642-design-graph-with-shortest-path-calculator.md
          - career/leetcode/daily/nov2023/2785-sort-vowels-in-a-string.md
          - career/leetcode/daily/nov2023/1930-unique-length-3-palindromic-subsequences.md
          - career/leetcode/daily/nov2023/1846-maximum-element-after-decreasing-and-rearranging.md
          - career/leetcode/daily/nov2023/1980-find-unique-binary-string.md
          - career/leetcode/daily/nov2023/1877-minimize-maximum-pair-sum-in-array.md
          - career/leetcode/daily/nov2023/1838-frequency-of-the-most-frequent-element.md
          - career/leetcode/daily/nov2023/1887-reduction-operations-to-make-the-array-elements-equal.md
          - career/leetcode/daily/nov2023/2391-minimum-amount-of-time-to-collect-garbage.md
          - career/leetcode/daily/1814-count-nice-pairs-in-an-array.md
    - System Design:
      - career/system-design/index.md
      - ByteByteGo: 
        - career/system-design/bytebytego/bytebytego-system-design.md
        - career/system-design/bytebytego/01-database-isolation-levels.md
    - Embedded:
      - career/embedded/configure-case-sensitivity-of-file-system.md
    - career/oop-basics.md
  - Life: 
    - life/index.md
  - Tags: tags.md
  
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg