site_name: Justin Hsiung's Space
theme:
  name: material
  custom_dir: overrides
  palette: 
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  logo: assets/bear-head-svgrepo-com.svg
  favicon: assets/bear-head-svgrepo-com.svg
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.footer
    - navigation.top
plugins:
  - tags:
      tags_file: tags.md
  - search:
      lang: en
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/JustinBear99
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/hsien-feng-hsiung/
nav:
  - Home: index.md
  - Career:
    - career/index.md
    - Leet Code:
      - career/leetcode/index.md
      - career/leetcode/823-binary-trees-with-factors.md
      - career/leetcode/5-longest-palindromic-substring.md
      - career/leetcode/1220-count-vowels-permutation.md
    - System Design:
      - career/system-design/index.md
      - ByteByteGo: 
        - career/system-design/bytebytego/bytebytego-system-design.md
  - Life: 
    - life/index.md
  - Tags: tags.md
  
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences